modified README.md

diff --git a/Project-1/call_scripts b/Project-1/call_scripts
--- a/Project-1/call_scripts
+++ b/Project-1/call_scripts
@@ -1,17 +1,80 @@
 #!/bin/bash
 
+# Check if the script is run as root 
+
+if [[ $EUID -ne 0 ]]; then
+  echo "Error: Run the file as root."
+  exit 1
+# Error handle: Return a non-zero exit code when error happened
+fi
+
+# Initiate variables to identify user option
+generate_list_package=false
+install_package=false
+symbolic_link=false
+
+while getopts "gil" opt; do
+# 'il': possible options, no need to pass in arguments
+  case $opt in
+    g)
+    #When user pass in '-g' option, change generate_list_package to True
+      generate_list_package=true
+      ;;
+    i)
+    # When user pass in '-i' option, change install_packages to True
+      install_package=true
+      ;;
+
+    l)
+    # When user pass in '-l' option, change install_opt to True
+      symbolic_link=true
+      ;;
+    *)
+    # When other arguments occur, display the user_guide function again showing the syntax
+      user_guide
+      ;;
+  esac
+done
+
+
 # Run the script containing list of packages 
-echo "Generating package list..."
-./generate_list_packages # this will run this script from the current directory
+if $generate_list_package; then
+	echo "Generating package list...."
+	if ./generate_list_packages; then
+		echo "Generated the list successfully"
+	else
+		echo "ERROR: could not generate list"
+	fi
+fi
+
 
 # Run the script with the installing details
-echo "Running package installation..."
-./install_packages # this will read the content from the packages.txt file and then install the listed packages
+if $install_package; then
+	echo "Running package installation..."
+	if ./install_packages; then
+		echo "Packages installed successfully"
+	else
+		echo "ERROR: could not install the packages"
+
+	fi
+fi
+
 
 # Run the symbolic links creation script
-echo "Creating symbolic links for configuration files..."
-./symbolic_links # will create the symbolic link from the config files in our repository to correct location
+if  $symbolic_link; then
+	echo "Creating symbolic links..."
+	if ./symbolic_link; then
+		echo "Symbolic link created successfully"
+	else
+		echo "ERROR: could not create symbolic link for config files"
+	fi
+fi
 
-# Confirmation message
-echo "System setup complete."
+# If neither option is given by user, show user_guide to display syntax
+if ! $generate_list_package && ! $install_packages && ! $create_links; then
+  user_guide
+else
+	echo "System setup complete" #Confirmation message
+fi
+
 
diff --git a/Project-1/install_packages b/Project-1/install_packages
--- a/Project-1/install_packages
+++ b/Project-1/install_packages
@@ -6,14 +6,18 @@ check_root() {
 	if [[ $EUID -ne 0 ]]; then
 		echo "This script must run as root"
 		exit 1
+	#Error Handle: returns a non-zero exit code when error happened
 	fi
 }
+
+# Ref: man bash, /EUID section
 
 # Function to verify that packages_list.txt exists
 check_package_list() {
     if [[ ! -f list_packages.txt ]]; then # checking the file
         echo "Error: list_packages.txt not found!"
-        exit 1
+        exit 1,
+	#Error Handle: returns a non-zero exit code if no such file found
     fi
 }
 
@@ -24,9 +28,13 @@ install_packages() {
         if [[ -n "$package" ]]; then  # Ensure that the variable package is not empty
             echo "Installing $package..."
             pacman -S --noconfirm "$package" || echo "Failed to install $package" # Install the package and says yes to to prompts automatically
+	# Error Handle: if package failed to install will throw an error
         fi
     done < list_packages.txt # to redirect the .txt file to read each line from the file
 }
+
+# Ref: https://unix.stackexchange.com/questions/26784/understanding-ifs
+# Ref: https://man.archlinux.org/man/pacman.8.en
 
 # Call functions in the necessary order
 check_root          # Check for root permissions
